# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1aabcdc76221f32ba0c39616aaa9c863cd9e5040ca423d6b89ca138b20af8ca7478a26a62ffb7eff3cdfaab5760054cdf5f82dfefcdae0654063d12c4ef97926

test:
  secret_key_base: 13bc09c11f56dc8c8774c8d4fd61b65d31b917ae31e15deee76656f4714151674a17f9b7c1981d1f38fbfcb775c2b72d5358b3af487e8a950141b46e76643293

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
